name: travelapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  device_preview: 1.2.0
   # state-management
  provider: ^6.0.5
  firebase_core: ^3.13.0
  # key-value storage
  shared_preferences: ^2.1.1
  cloud_firestore: ^5.6.7
  path_provider: ^2.0.15
  file_selector: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/         # <-- note the trailing slash
    - assets/places.json
    - assets/saved_trips.json
    - assets/users.json
    - assets/photos/        # <-- trailing slash here too
    - assets/photos/Adventure/Peak District National Park/1.jpg
    - assets/photos/Adventure/Peak District National Park/2.jpg
    - assets/photos/Adventure/Peak District National Park/3.jpg
    - assets/photos/Adventure/Peak District National Park/4.jpg
    - assets/photos/Adventure/Snowdonia Adventure Activities/1.jpg
    - assets/photos/Adventure/Snowdonia Adventure Activities/2.jpeg
    - assets/photos/Adventure/Snowdonia Adventure Activities/3.jpg
    - assets/photos/Adventure/Snowdonia Adventure Activities/4.jpg
    - assets/photos/Adventure/Go Ape Forest Adventure - Sherwood Pines/1.jpg
    - assets/photos/Adventure/Go Ape Forest Adventure - Sherwood Pines/2.jpg
    - assets/photos/Adventure/Go Ape Forest Adventure - Sherwood Pines/3.jpg
    - assets/photos/Adventure/Go Ape Forest Adventure - Sherwood Pines/4.jpg
    - assets/photos/Adventure/walk/1.jpg
    - assets/photos/Adventure/walk/2.jpg
    - assets/photos/Adventure/walk/3.jpg
    - assets/photos/Adventure/walk/4.jpg
    - assets/photos/Adventure/Adventure Parc Snowdonia/1.jpg
    - assets/photos/Adventure/Adventure Parc Snowdonia/2.jpg
    - assets/photos/Adventure/Adventure Parc Snowdonia/3.jpg
    - assets/photos/Adventure/Adventure Parc Snowdonia/4.jpg_large
    - assets/photos/Beach/Bournemouth/1.jpg
    - assets/photos/Beach/Bournemouth/2.avif
    - assets/photos/Beach/Bournemouth/3.jpg
    - assets/photos/Beach/Bournemouth/4.jpg
    - assets/photos/Beach/Bournemouth/5.jpg
    - assets/photos/Beach/Fistral Beach/1.jpg
    - assets/photos/Beach/Fistral Beach/2.jpg
    - assets/photos/Beach/Fistral Beach/3.jpg
    - assets/photos/Beach/Fistral Beach/4.jpg
    - assets/photos/Beach/Brighton Beach/1.webp
    - assets/photos/Beach/Brighton Beach/2.avif
    - assets/photos/Beach/Brighton Beach/3.jpg
    - assets/photos/Beach/Brighton Beach/4.jpg
    - assets/photos/Beach/Woolacombe Beach/1.jpg
    - assets/photos/Beach/Woolacombe Beach/2.jpeg
    - assets/photos/Beach/Woolacombe Beach/3.jpg
    - assets/photos/Beach/Woolacombe Beach/4.jpg
    - assets/photos/Beach/Camber Sands/1.jpg
    - assets/photos/Beach/Camber Sands/2.jpg
    - assets/photos/Beach/Camber Sands/3.jpg
    - assets/photos/Beach/Camber Sands/4.webp
    - assets/photos/lake/Lake Windermere/1.webp
    - assets/photos/lake/Lake Windermere/2.jpg
    - assets/photos/lake/Lake Windermere/3.jpg
    - assets/photos/lake/Lake Windermere/4.jpg
    - assets/photos/lake/Coniston Water/1.jpg
    - assets/photos/lake/Coniston Water/2.jpg
    - assets/photos/lake/Coniston Water/3.jpg
    - assets/photos/lake/Coniston Water/4.jpg
    - assets/photos/lake/Derwentwater/1.jpg
    - assets/photos/lake/Derwentwater/2.jpg
    - assets/photos/lake/Derwentwater/3.jpg
    - assets/photos/lake/Derwentwater/4.jpg
    - assets/photos/lake/Buttermere/1.jpg
    - assets/photos/lake/Buttermere/2.jpg
    - assets/photos/lake/Buttermere/3.jpg
    - assets/photos/lake/Buttermere/4.jpg
    - assets/photos/lake/Ullswater/1.jpg
    - assets/photos/lake/Ullswater/2.jpg
    - assets/photos/lake/Ullswater/3.jpg
    - assets/photos/lake/Ullswater/4.jpg
    - assets/photos/Mountain/Scafell Pike/1.jpg
    - assets/photos/Mountain/Scafell Pike/2.jpg
    - assets/photos/Mountain/Scafell Pike/3.jpg
    - assets/photos/Mountain/Scafell Pike/4.jpg
    - assets/photos/Mountain/Helvellyn/1.jpg
    - assets/photos/Mountain/Helvellyn/2.jpg
    - assets/photos/Mountain/Helvellyn/3.webp
    - assets/photos/Mountain/Helvellyn/4.jpg
    - assets/photos/Mountain/The Cheviot/1.jpg
    - assets/photos/Mountain/The Cheviot/2.jpg
    - assets/photos/Mountain/The Cheviot/3.webp
    - assets/photos/Mountain/The Cheviot/4.jpg
    - assets/photos/Mountain/Pen-y-Ghent/1.jpg
    - assets/photos/Mountain/Pen-y-Ghent/2.jpg
    - assets/photos/Mountain/Pen-y-Ghent/3.jpg
    - assets/photos/Mountain/Pen-y-Ghent/4.jpg
    - assets/photos/Mountain/Blencathra (Saddleback)/1.jpg
    - assets/photos/Mountain/Blencathra (Saddleback)/2.jpg
    - assets/photos/Mountain/Blencathra (Saddleback)/3.jpg
    - assets/photos/Mountain/Blencathra (Saddleback)/4.jpg
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
