platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# Workaround: define the missing method inline
def flutter_install_all_ios_pods(ios_project_path)
  flutter_application_path = File.expand_path('..', __dir__)
  load File.join(flutter_application_path, '.flutter-plugins-dependencies')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
